'use client'
import { useEffect,useState } from 'react'
import { createClient } from '@/lib/supabase-browser'
type Source={title:string,url:string,type:string,snippet:string}
export default function Dashboard(){
 const [providerToken,setProviderToken]=useState(''); const [email,setEmail]=useState(''); const [q,setQ]=useState(''); const [answer,setAnswer]=useState(''); const [sources,setSources]=useState<Source[]>([]); const [loading,setLoading]=useState(false); const [err,setErr]=useState('')
 useEffect(()=>{(async()=>{const supabase=createClient(); const {data}=await supabase.auth.getSession(); if(!data.session){location.href='/';return}; setEmail(data.session.user.email||''); setProviderToken(data.session.provider_token||'')})()},[])
 async function search(){setLoading(true);setErr('');setAnswer('');setSources([]);try{const r=await fetch('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:q,providerToken})});const j=await r.json();if(!r.ok) throw new Error(j.error||'Search failed');setAnswer(j.answer);setSources(j.sources||[])}catch(e:any){setErr(e.message)}finally{setLoading(false)}}
 async function checkout(){const r=await fetch('/api/stripe/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email})});const j=await r.json(); if(j.url) location.href=j.url; else setErr(j.error||'Checkout unavailable')}
 return <div className="dashboard"><aside className="side"><div className="logo">Tiny<span>Glean</span></div><div className="connect"><span className="status">✓ Gmail connected</span><span className="status">✓ Drive connected</span></div><p className="small">{email}</p><button className="pill" onClick={checkout}>Upgrade — £49/mo</button></aside><main className="main"><div className="eyebrow">Company search</div><h1>What do you want to know?</h1><div className="searchbox"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="e.g. What did we quote Acme?"/><button disabled={loading||!q||!providerToken} onClick={search}>{loading?'Searching…':'Search'}</button></div>{!providerToken&&<p className="error">Google access token missing. Sign out and reconnect Google with the requested permissions.</p>}{err&&<p className="error">{err}</p>}{answer&&<section className="answer"><strong>Answer</strong><p>{answer}</p><div className="sources">{sources.map((s,i)=><a className="source" href={s.url} target="_blank" rel="noreferrer" key={i}><strong>{s.title}</strong><div className="small">{s.type} · {s.snippet}</div></a>)}</div></section>}</main></div>
}
